// <auto-generated />
using System;
using CannonPacking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CannonPacking.Infrastructure.Migrations
{
    [DbContext(typeof(PackingDbContext))]
    [Migration("20260320211725_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CannonPacking.Domain.Entities.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoxCode")
                        .IsUnique();

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("CannonPacking.Domain.Entities.Towel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Towels");
                });

            modelBuilder.Entity("CannonPacking.Domain.Entities.Towel", b =>
                {
                    b.HasOne("CannonPacking.Domain.Entities.Box", "Box")
                        .WithMany("Towels")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Box");
                });

            modelBuilder.Entity("CannonPacking.Domain.Entities.Box", b =>
                {
                    b.Navigation("Towels");
                });
#pragma warning restore 612, 618
        }
    }
}
